I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 36, in script call
    call opening
  File "game/scripts/script.rpy", line 95, in script
    n "you have [ikida] ikida point. test."
KeyError: u'ikida'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 36, in script call
    call opening
  File "game/scripts/script.rpy", line 95, in script
    n "you have [ikida] ikida point. test."
  File "E:\Work\VisualNovel\renpy-6.18.3-sdk\renpy\ast.py", line 593, in execute
    renpy.exports.say(who, what, interact=self.interact)
  File "E:\Work\VisualNovel\renpy-6.18.3-sdk\renpy\exports.py", line 1033, in say
    who(what, interact=interact)
  File "E:\Work\VisualNovel\renpy-6.18.3-sdk\renpy\character.py", line 817, in __call__
    what = what_pattern.replace("[what]", sub(what, translate=translate))
  File "E:\Work\VisualNovel\renpy-6.18.3-sdk\renpy\character.py", line 799, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "E:\Work\VisualNovel\renpy-6.18.3-sdk\renpy\substitutions.py", line 229, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 543, in vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 565, in _vformat
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 626, in get_field
  File "/home/tom/ab/x64lucid-deps/install/lib/python2.7/string.py", line 585, in get_value
KeyError: u'ikida'

Windows-8-6.2.9200
Ren'Py 6.99.1.329
GreenT 0.0
